version: "3"
services:
  server-docker:
    image: server-docker
    container_name: server-docker
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data:
    driver: local
