version: "3"
services:
  portfolio_server_baviske:
    # image: docker.io/baviske/portfolio_server_baviske:latest
    image: portfolio_server_baviske
    container_name: portfolio_server_baviske
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
volumes:
  data:
    driver: local
